[package]
name = "event_collision_across_templates"
type = "contract"
authors = ["Wonderland"]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { path = "../../../../aztec-nr/aztec" }
template_composition = { path = "../../../lib" }
composition_fixtures = { path = "../../../composition_tests/fixtures" }
